package org.oettel.model.message;

public enum ClientMessageType {
    CHAT_MESSAGE, CLIENT_BROADCAST, CLIENT_BROADCAST_RESPONSE, LEADER_ANNOUNCEMENT,VECTOR_BROADCAST_RESPONSE,
    NACK, REPLICATION

}
