package org.oettel.model.message;

public enum ServerMessageType {
    BROADCAST, BROADCAST_RESPONSE, HEARTBEAT,
    HEARTBEAT_RESPONSE,
    ELECTION_INITIATING_MESSAGE, ELECTION_MESSAGE, LEADER_MESSAGE,
    LEADER_ANNOUNCEMENT
}
